name: survey
description: "Planning E-Report"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  cached_network_image: ^3.2.3
  open_file: ^3.2.1
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^17.1.2
  qr_flutter: ^4.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"
